# Generated by Django 3.2.7 on 2021-09-26 03:29

from django.db import migrations, models
import django.db.models.deletion
import feedback.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created', models.DateTimeField(default=feedback.models.utc_now, verbose_name='Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Order')),
                ('text', models.TextField(default='', verbose_name='Text')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('current', models.BooleanField(default=True, verbose_name='Current')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('qtype', models.PositiveSmallIntegerField(choices=[(1, 'Free Response'), (2, 'Multiple Choice')], verbose_name='Question Type')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question')),
                ('selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.multichoiceoption')),
            ],
        ),
        migrations.AddField(
            model_name='multichoiceoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question'),
        ),
        migrations.CreateModel(
            name='FreeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='Response')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question')),
            ],
        ),
    ]
