# Generated by Django 3.2.7 on 2021-09-26 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='pagecopy',
            options={'verbose_name': 'Feedback Page Intro'},
        ),
        migrations.AddField(
            model_name='multichoiceoption',
            name='text2',
            field=models.CharField(default='', max_length=280, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Free Response'), (2, 'Multiple Choice')], default=1, verbose_name='Question Type'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Free Response')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question')),
                ('selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.multichoiceoption')),
            ],
            options={
                'ordering': ['question__order'],
            },
        ),
    ]
