# Generated by Django 3.2.7 on 2021-09-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='pagecopy',
            options={'verbose_name': 'Feedback Page Intro'},
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Free Response'), (2, 'Multiple Choice')], default=1, verbose_name='Question Type'),
        ),
    ]
