# Generated by Django 3.2.7 on 2021-09-26 23:38

from django.db import migrations

def copy_option_text(apps, schema_editor):
    MCO = apps.get_model('feedback', 'MultiChoiceOption')
    for option in MCO.objects.all():
        option.text2 = option.text[:280]
        option.save()

class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20210926_2336'),
    ]

    operations = [
        migrations.RunPython(copy_option_text)
    ]
