# Generated by Django 3.2.7 on 2021-09-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20210926_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoiceoption',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Weight'),
        ),
    ]
