# Generated by Django 3.2.7 on 2021-09-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20210926_2338'),
        ('feedback', '0005_auto_20210926_1023'),
    ]

    operations = [
    ]
