# Generated by Django 3.2.7 on 2021-09-27 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_merge_0003_auto_20210926_2338_0005_auto_20210926_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedback'),
        ),
    ]
