# Generated by Django 3.2.7 on 2021-09-27 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_response_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedback'),
        ),
    ]
