# Generated by Django 3.0.10 on 2020-09-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Born')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Died')),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('executed', models.IntegerField(verbose_name='Year Executed')),
                ('medium', models.CharField(max_length=255, verbose_name='Medium')),
                ('dimensions', models.CharField(max_length=255, verbose_name='Dimensions')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Artist')),
            ],
            options={
                'verbose_name': 'Art Work',
                'verbose_name_plural': 'Art Works',
                'db_table': 'artworks',
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('collected', models.BooleanField(default=False, verbose_name='Artworks collected')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
            ],
            options={
                'db_table': 'auctions',
            },
        ),
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.IntegerField(verbose_name='Lot Number')),
                ('estimate_low', models.IntegerField(verbose_name='Estimate Low Value')),
                ('estimate_high', models.IntegerField(verbose_name='Estimate High Value')),
                ('estimate_currency', models.CharField(default='USD', max_length=3, verbose_name='Estimate Currency')),
                ('sale_price', models.IntegerField(verbose_name='Sale Price')),
                ('sale_currency', models.CharField(default='USD', max_length=3, verbose_name='Sale Currency')),
                ('number_of_bids', models.IntegerField(default=1, verbose_name='Number of Bids')),
                ('reserve_met', models.BooleanField(default=True, verbose_name='Reserve Met')),
                ('condition_report', models.TextField(default='', verbose_name='Condition Report')),
                ('provenance', models.TextField(default='', verbose_name='Provenance')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Artwork')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Auction')),
            ],
            options={
                'verbose_name': 'Auction Lot',
                'verbose_name_plural': 'Auction Lots',
                'db_table': 'auction_lots',
            },
        ),
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured Photo')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Artwork')),
            ],
            options={
                'verbose_name': 'Art Image',
                'verbose_name_plural': 'Art Images',
                'db_table': 'art_images',
            },
        ),
    ]
