# Generated by Django 3.0.10 on 2020-10-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='url',
            field=models.URLField(max_length=800, unique=True, verbose_name='URL'),
        ),
    ]
