# Generated by Django 3.0.10 on 2020-10-01 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201001_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlot',
            name='visited',
            field=models.BooleanField(default=False, verbose_name='Visited'),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Artwork'),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='estimate_high',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimate High Value'),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='estimate_low',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimate Low Value'),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sale Price'),
        ),
    ]
