# Generated by Django 3.0.10 on 2021-01-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201001_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionlot',
            options={'ordering': ['auction__id', 'lot_number'], 'verbose_name': 'Auction Lot', 'verbose_name_plural': 'Auction Lots'},
        ),
        migrations.AddField(
            model_name='artist',
            name='name_slug',
            field=models.SlugField(default='', editable=False, max_length=255, verbose_name='Name Slug'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='title_slug',
            field=models.SlugField(default='', editable=False, max_length=255, verbose_name='Title Slug'),
        ),
    ]
