# Generated by Django 3.0.10 on 2021-01-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auction_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlot',
            name='lot_number',
            field=models.CharField(default='', max_length=20, verbose_name='Lot Number'),
        ),
    ]
