# Generated by Django 3.0.10 on 2021-01-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210116_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlot',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='auctionlot',
            name='title',
            field=models.CharField(default='', max_length=1000, verbose_name='Title'),
        ),
    ]
