# Generated by Django 3.0.10 on 2021-01-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210120_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlot',
            name='collected',
            field=models.BooleanField(default=False, verbose_name='Collected'),
        ),
    ]
