# Generated by Django 3.0.10 on 2021-01-25 11:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_lotimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlot',
            name='sale_price_usd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sale Price in USD'),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='condition_report',
            field=models.TextField(blank=True, default='', verbose_name='Condition Report'),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='provenance',
            field=models.TextField(blank=True, default='', verbose_name='Provenance'),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='reserve_met',
            field=models.BooleanField(default=False, verbose_name='Reserve Met'),
        ),
        migrations.AlterField(
            model_name='lotimage',
            name='image',
            field=models.ImageField(upload_to=main.models.lot_image_path),
        ),
    ]
